osx_image: xcode9

language: swift

xcode_workspace: Smack\ -\ a\ Slack\ clone.xcworkspace
xcode_scheme: Smack\ -\ a\ Slack\ clone
xcode_sdk: iphonesimulator10.2


# blocklist
branches:
  except:
  - legacy
  - experimental

#script: xcodebuild -project Dev-Profile/dev-profile/dev-profile8.xcodeproj -scheme dev-profile8 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
script: xcodebuild -project Smack\ -\ a\ Slack\ clone.xcodeproj -scheme Smack\ -\ a\ Slack\ clone -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
  email: true
