osx_image: xcode9

language: swift

xcode_workspace: Smack/Smack-a-Slack-Clone/Smack-a-Slack-Clone.xcworkspace
xcode_scheme: Smack-a-Slack-Clone
xcode_sdk: iphonesimulator10.2
podfile: Smack/Smack-a-Slack-Clone/Podfile


# blocklist
branches:
  except:
  - legacy
  - experimental

#script: xcodebuild -project Dev-Profile/dev-profile/dev-profile8.xcodeproj -scheme dev-profile8 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
script: xcodebuild -project Smack/Smack-a-Slack-Clone/Smack-a-Slack-Clone.xcodeproj -scheme Smack-a-Slack-Clone -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
  email: true
