osx_image: xcode8.3
language: swift
xcode_project: Dev-Profile/dev-profile8.xcodeproj
xcode_scheme: dev-profile8
xcode_sdk: iphonesimulator10.2

before_install:
- brew install yarn

# blocklist
branches:
  except:
  - legacy
  - experimental


script: xcodebuild -project NAME.xcodeproj -scheme NAME -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
  email: true
