osx_image: xcode9
language: swift
#xcode_project: Dev-Profile/dev-profile/dev-profile8.xcodeproj
#xcode_scheme: dev-profile8
xcode_project: Window-Shopper/Window-Shopper/Window-Shopper.xcodeproj
xcode_scheme: Window-Shopper
xcode_sdk: iphonesimulator10.2

before_install:
- brew install yarn

# blocklist
branches:
  except:
  - legacy
  - experimental


#script: xcodebuild -project Dev-Profile/dev-profile/dev-profile8.xcodeproj -scheme dev-profile8 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
script: xcodebuild -project Window-Shopper/Window-Shopper/Window-Shopper.xcodeproj -scheme Window-Shopper -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
  email: true
